name: community_internal
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.19
  cloud_firestore: ^3.1.17
  bottom_navy_bar: ^6.0.0
  font_awesome_flutter: ^10.1.0
  carousel_slider: ^4.1.1
  cached_network_image: ^3.2.0
  flutter_tags: "^1.0.0-nullsafety.1"
  image_form_field: ^1.0.0-nullsafety.0
  settings_ui: ^2.0.2
  readmore: ^2.1.0
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
     - family: Caladea
       fonts:
         - asset: assets/fonts/Caladea/Caladea-Regular.ttf
         - asset: assets/fonts/Caladea/Caladea-Bold.ttf
           weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

